-- AMD
INSERT INTO dbo.AMD_Gold (Date, AMD_Close, AMD_SMA10, AMD_SMA50, AMD_SMA100, AMD_ZScore20, AMD_DailyRet, AMD_Volatility20)
SELECT Date, AMD_Close, AMD_SMA10, AMD_SMA50, AMD_SMA100, AMD_ZScore20, AMD_DailyRet, AMD_Volatility20
FROM dbo.AMD_temp;
DROP TABLE dbo.AMD_temp;


-- AMZN
INSERT INTO dbo.AMZN_Gold (Date, AMZN_Close, AMZN_SMA10, AMZN_SMA50, AMZN_SMA100, AMZN_ZScore20, AMZN_DailyRet, AMZN_Volatility20)
SELECT Date, AMZN_Close, AMZN_SMA10, AMZN_SMA50, AMZN_SMA100, AMZN_ZScore20, AMZN_DailyRet, AMZN_Volatility20
FROM dbo.AMZN_temp;
DROP TABLE dbo.AMZN_temp;

-- AVGO
INSERT INTO dbo.AVGO_Gold (Date, AVGO_Close, AVGO_SMA10, AVGO_SMA50, AVGO_SMA100, AVGO_ZScore20, AVGO_DailyRet, AVGO_Volatility20)
SELECT Date, AVGO_Close, AVGO_SMA10, AVGO_SMA50, AVGO_SMA100, AVGO_ZScore20, AVGO_DailyRet, AVGO_Volatility20
FROM dbo.AVGO_temp;
DROP TABLE dbo.AVGO_temp;

-- GOOG
INSERT INTO dbo.GOOG_Gold (Date, GOOG_Close, GOOG_SMA10, GOOG_SMA50, GOOG_SMA100, GOOG_ZScore20, GOOG_DailyRet, GOOG_Volatility20)
SELECT Date, GOOG_Close, GOOG_SMA10, GOOG_SMA50, GOOG_SMA100, GOOG_ZScore20, GOOG_DailyRet, GOOG_Volatility20
FROM dbo.GOOG_temp;
DROP TABLE dbo.GOOG_temp;

-- META
INSERT INTO dbo.META_Gold (Date, META_Close, META_SMA10, META_SMA50, META_SMA100, META_ZScore20, META_DailyRet, META_Volatility20)
SELECT Date, META_Close, META_SMA10, META_SMA50, META_SMA100, META_ZScore20, META_DailyRet, META_Volatility20
FROM dbo.META_temp;
DROP TABLE dbo.META_temp;

-- MSFT
INSERT INTO dbo.MSFT_Gold (Date, MSFT_Close, MSFT_SMA10, MSFT_SMA50, MSFT_SMA100, MSFT_ZScore20, MSFT_DailyRet, MSFT_Volatility20)
SELECT Date, MSFT_Close, MSFT_SMA10, MSFT_SMA50, MSFT_SMA100, MSFT_ZScore20, MSFT_DailyRet, MSFT_Volatility20
FROM dbo.MSFT_temp;
DROP TABLE dbo.MSFT_temp;

-- NVDA
INSERT INTO dbo.NVDA_Gold (Date, NVDA_Close, NVDA_SMA10, NVDA_SMA50, NVDA_SMA100, NVDA_ZScore20, NVDA_DailyRet, NVDA_Volatility20)
SELECT Date, NVDA_Close, NVDA_SMA10, NVDA_SMA50, NVDA_SMA100, NVDA_ZScore20, NVDA_DailyRet, NVDA_Volatility20
FROM dbo.NVDA_temp;
DROP TABLE dbo.NVDA_temp;

-- ORCL
INSERT INTO dbo.ORCL_Gold (Date, ORCL_Close, ORCL_SMA10, ORCL_SMA50, ORCL_SMA100, ORCL_ZScore20, ORCL_DailyRet, ORCL_Volatility20)
SELECT Date, ORCL_Close, ORCL_SMA10, ORCL_SMA50, ORCL_SMA100, ORCL_ZScore20, ORCL_DailyRet, ORCL_Volatility20
FROM dbo.ORCL_temp; 
DROP TABLE dbo.ORCL_temp;

-- PANW
INSERT INTO dbo.PANW_Gold (Date, PANW_Close, PANW_SMA10, PANW_SMA50, PANW_SMA100, PANW_ZScore20, PANW_DailyRet, PANW_Volatility20)
SELECT Date, PANW_Close, PANW_SMA10, PANW_SMA50, PANW_SMA100, PANW_ZScore20, PANW_DailyRet, PANW_Volatility20
FROM dbo.PANW_temp;
DROP TABLE dbo.PANW_temp;