-- Tickers list


-- NVDA, META, AMZN, PANW, ORCL, AMD, GOOG, MSFT, AVGO

-- 1. NVDA
CREATE TABLE [dbo].[NVDA_Gold] (
    [Date] DATE NOT NULL,
    [NVDA_Close] DECIMAL(18, 8),
    [NVDA_SMA10] DECIMAL(18, 8),
    [NVDA_SMA50] DECIMAL(18, 8),
    [NVDA_SMA100] DECIMAL(18, 8),
    [NVDA_ZScore20] DECIMAL(18, 8),
    [NVDA_DailyRet] DECIMAL(18, 8),
    [NVDA_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[NVDA_Gold] ADD CONSTRAINT PK_NVDA PRIMARY KEY CLUSTERED ([Date]);

-- 2. META
CREATE TABLE [dbo].[META_Gold] (
    [Date] DATE NOT NULL,
    [META_Close] DECIMAL(18, 8),
    [META_SMA10] DECIMAL(18, 8),
    [META_SMA50] DECIMAL(18, 8),
    [META_SMA100] DECIMAL(18, 8),
    [META_ZScore20] DECIMAL(18, 8),
    [META_DailyRet] DECIMAL(18, 8),
    [META_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[META_Gold] ADD CONSTRAINT PK_META PRIMARY KEY CLUSTERED ([Date]);

-- 3. AMZN
CREATE TABLE [dbo].[AMZN_Gold] (
    [Date] DATE NOT NULL,
    [AMZN_Close] DECIMAL(18, 8),
    [AMZN_SMA10] DECIMAL(18, 8),
    [AMZN_SMA50] DECIMAL(18, 8),
    [AMZN_SMA100] DECIMAL(18, 8),
    [AMZN_ZScore20] DECIMAL(18, 8),
    [AMZN_DailyRet] DECIMAL(18, 8),
    [AMZN_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[AMZN_Gold] ADD CONSTRAINT PK_AMZN PRIMARY KEY CLUSTERED ([Date]);

-- 4. PANW
CREATE TABLE [dbo].[PANW_Gold] (
    [Date] DATE NOT NULL,
    [PANW_Close] DECIMAL(18, 8),
    [PANW_SMA10] DECIMAL(18, 8),
    [PANW_SMA50] DECIMAL(18, 8),
    [PANW_SMA100] DECIMAL(18, 8),
    [PANW_ZScore20] DECIMAL(18, 8),
    [PANW_DailyRet] DECIMAL(18, 8),
    [PANW_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[PANW_Gold] ADD CONSTRAINT PK_PANW PRIMARY KEY CLUSTERED ([Date]);

-- 5. ORCL
CREATE TABLE [dbo].[ORCL_Gold] (
    [Date] DATE NOT NULL,
    [ORCL_Close] DECIMAL(18, 8),
    [ORCL_SMA10] DECIMAL(18, 8),
    [ORCL_SMA50] DECIMAL(18, 8),
    [ORCL_SMA100] DECIMAL(18, 8),
    [ORCL_ZScore20] DECIMAL(18, 8),
    [ORCL_DailyRet] DECIMAL(18, 8),
    [ORCL_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[ORCL_Gold] ADD CONSTRAINT PK_ORCL PRIMARY KEY CLUSTERED ([Date]);

-- 6. AMD
CREATE TABLE [dbo].[AMD_Gold] (
    [Date] DATE NOT NULL,
    [AMD_Close] DECIMAL(18, 8),
    [AMD_SMA10] DECIMAL(18, 8),
    [AMD_SMA50] DECIMAL(18, 8),
    [AMD_SMA100] DECIMAL(18, 8),
    [AMD_ZScore20] DECIMAL(18, 8),
    [AMD_DailyRet] DECIMAL(18, 8),
    [AMD_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[AMD_Gold] ADD CONSTRAINT PK_AMD PRIMARY KEY CLUSTERED ([Date]);

-- 7. GOOG
CREATE TABLE [dbo].[GOOG_Gold] (
    [Date] DATE NOT NULL,
    [GOOG_Close] DECIMAL(18, 8),
    [GOOG_SMA10] DECIMAL(18, 8),
    [GOOG_SMA50] DECIMAL(18, 8),
    [GOOG_SMA100] DECIMAL(18, 8),
    [GOOG_ZScore20] DECIMAL(18, 8),
    [GOOG_DailyRet] DECIMAL(18, 8),
    [GOOG_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[GOOG_Gold] ADD CONSTRAINT PK_GOOG PRIMARY KEY CLUSTERED ([Date]);

-- 8. MSFT
CREATE TABLE [dbo].[MSFT_Gold] (
    [Date] DATE NOT NULL,
    [MSFT_Close] DECIMAL(18, 8),
    [MSFT_SMA10] DECIMAL(18, 8),
    [MSFT_SMA50] DECIMAL(18, 8),
    [MSFT_SMA100] DECIMAL(18, 8),
    [MSFT_ZScore20] DECIMAL(18, 8),
    [MSFT_DailyRet] DECIMAL(18, 8),
    [MSFT_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[MSFT_Gold] ADD CONSTRAINT PK_MSFT PRIMARY KEY CLUSTERED ([Date]);

-- 9. AVGO
CREATE TABLE [dbo].[AVGO_Gold] (
    [Date] DATE NOT NULL,
    [AVGO_Close] DECIMAL(18, 8),
    [AVGO_SMA10] DECIMAL(18, 8),
    [AVGO_SMA50] DECIMAL(18, 8),
    [AVGO_SMA100] DECIMAL(18, 8),
    [AVGO_ZScore20] DECIMAL(18, 8),
    [AVGO_DailyRet] DECIMAL(18, 8),
    [AVGO_Volatility20] DECIMAL(18, 8)
);
ALTER TABLE [dbo].[AVGO_Gold] ADD CONSTRAINT PK_AVGO PRIMARY KEY CLUSTERED ([Date]);